
import type { IntentCategory, IntentClassification } from "./intent-classifier";

export interface IntentRule {
  category: IntentCategory;
  patterns: RegExp[];
  tool: string | null;
  query: string | null;
  confidence: "alta" | "media";
  extraCheck?: (msg: string) => boolean;
}

export const INTENT_RULES: IntentRule[] = [
  {
    category: "INFO_EMPRESA",
    tool: null,
    query: null,
    confidence: "alta",
    patterns: [
      /red(es|es\s*sociales?)\s*(de\s*)?(sisprot)?/i,
      /sisprot.*(red(es|es\s*sociales?)|instagram|youtube|whatsapp|facebook)/i,
      /(instagram|youtube|whatsapp|facebook).*(sisprot)/i,
      /canal\s*(de\s*)?youtube.*sisprot/i,
      /d[oó]nde\s*(los\s*)?(consigo|consigo\s*en|encuentro|veo).*(instagram|youtube|whatsapp|facebook)/i,
    ],
  },

  {
    category: "INFO_EMPRESA",
    tool: null,
    query: null,
    confidence: "alta",
    patterns: [
      /qu[ée]\s*(es|son)\s*sisprot/i,
      /sisprot.*qu[ée]/i,
      /informaci[óo]n.*empresa/i,
      /qui[ée]nes\s*son/i,
      /sobre\s*(ustedes|sisprot)/i,
      /conocer.*sisprot/i,
      /saber.*sisprot/i,
      /cu[ée]ntame.*sisprot/i,
      /d[ií]me.*sisprot/i,
    ],
  },

  {
    category: "INFO_PLANES",
    tool: null,
    query: null,
    confidence: "alta",
    patterns: [
      /qu[ée]\s*planes/i,
      /planes\s*(tienen|ofrecen|manejan|hay|disponibles|existen)/i,
      /tienen\s*planes/i,
      /ofrecen\s*planes/i,
      /planes?\s*(de\s*)?(internet|fibra)/i,
      /planes?\s*(residencial|hogar|empresa|pyme|negocio)/i,
      /los\s*planes/i,
      /sus\s*planes/i,
      /ver\s*planes/i,
      /conocer\s*(los\s*)?planes/i,
      /saber\s*(los\s*)?planes/i,
      /cu[aá]les\s*(son\s*)?(los\s*)?planes/i,
      /info(rmaci[oó]n)?\s*(de\s*)?planes/i,
      /lista\s*(de\s*)?planes/i,
      /cat[aá]logo\s*(de\s*)?planes/i,
      /decir(me)?\s*(qu[eé]\s*)?planes/i,

      /precio/i,
      /cu[áa]nto\s*cuesta/i,
      /tarifas?/i,
      /costo\s*(del?\s*)?(servicio|internet|plan)/i,
      /mensualidad/i,
      /valor\s*del?\s*plan/i,
      /que\s*precio\s*tienen/i,

      /paquetes?\s*(de\s*)?internet/i,
      /megas?\s*\d+/i,
      /\d+\s*megas?/i,
      /velocidad(es)?\s*(disponibles|que\s*ofrecen)/i,
      /fibra\s*(optica|simetrica)/i,

      // Detección de dispositivos y uso para asesoría de ventas
      /\d+\s*(dispositivos|equipos|celulares|telf|pcs|computadoras|televisores|tv|consolas|ps\d|xbox)/i,
      /(gamer|jugar|en\s*linea|streaming|netflix|4k|trabajar|home\s*office|zoom|videollamada|clases\s*online)/i,
    ],
  },

  {
    category: "INFO_COBERTURA",
    tool: null,
    query: null,
    confidence: "alta",
    patterns: [
      /cobertura/i,
      /zonas?\s*(disponibles|con\s*servicio)/i,
      /llegan?\s*(a|hasta)/i,
      /tienen\s*servicio\s*en/i,
      /disponibilidad/i,
      /hay\s*se[nñ]al/i,
      /sectores?/i,
    ],
  },

  {
    category: "INFO_PAGOS",
    tool: null,
    query: null,
    confidence: "alta",
    patterns: [
      /cuentas?\s*bancarias?/i,
      /datos?\s*(de\s*)?pago/i,
      /n[úu]meros?\s*(de\s*)?cuenta/i,
      /c[óo]mo\s*pag(o|ar)/i,
      /m[ée]todos?\s*(de\s*)?pago/i,
      /pago\s*m[óo]vil/i,
      /zelle/i,
      /transferencia/i,
      /d[oó]nde\s*pag(o|ar)/i,
      /reportar\s*(un\s*)?pago/i, /binance/i,
      /paypal/i,
      /pasarela/i,
    ],
  },

  {
    category: "INFO_ADMINISTRATIVO",
    tool: "search_knowledge_base",
    query: "devoluciones reembolsos",
    confidence: "alta",
    patterns: [
      /devoluci[óo]n/i,
      /reembolso/i,
      /pago\s*(duplicado|equivocado|incorrecto)/i,
      /pagu[ée]\s*(a\s*)?otra\s*cuenta/i,
      /cuenta\s*(incorrecta|equivocada)/i,
    ],
  },
  {
    category: "INFO_ADMINISTRATIVO",
    tool: "search_knowledge_base",
    query: "mudanzas cambio titular",
    confidence: "alta",
    patterns: [
      /mudan(za|me)/i,
      /cambio\s*(de\s*)?titular/i,
      /cambiar\s*(el\s*)?titular/i,
      /trasladar/i,
    ],
  },
  {
    category: "INFO_ADMINISTRATIVO",
    tool: "search_knowledge_base",
    query: "prorrateo ciclos facturaci\u00f3n",
    confidence: "alta",
    patterns: [
      /prorrateo/i,
      /ciclo\s*(de\s*)?facturaci[óo]n/i,
      /fecha\s*(de\s*)?(corte|pago|l[íi]mite)/i,
      /cu[áa]ndo\s*(me\s*)?cortan/i,
      /d[íi]a\s*(de\s*)?(corte|pago)/i,
    ],
  },

  {
    category: "INFO_INSTALACION",
    tool: "search_knowledge_base",
    query: "requisitos contrataci\u00f3n",
    confidence: "alta",
    patterns: [
      /requisitos?/i,
      /contrataci[óo]n/i,
      /contratar\s*(el\s*)?(servicio|internet|fibra)/i,
      /qu[ée]\s*necesito\s*(para)?/i,
      /documentos?\s*(para|necesarios)/i,
    ],
  },
  {
    category: "INFO_INSTALACION",
    tool: "search_knowledge_base",
    query: "instalaci\u00f3n costos promociones",
    confidence: "alta",
    patterns: [
      /instalaci[óo]n/i,
      /instalar(me)?\s*(el\s*)?(servicio|internet|fibra)?/i,
      /promoci[óo]n/i,
      /financiamiento/i,
      /cuotas?\s*(de\s*)?instalaci[óo]n/i,],
  },

  {
    category: "PROBLEMA_TECNICO",
    tool: "search_knowledge_base",
    query: "procedimiento falla internet",
    confidence: "alta",
    patterns: [
      /no\s*tengo\s*internet/i,
      /sin\s*internet/i,
      /revis(a|ar)\s*(me\s*)?(mi\s*)?(internet|conexi[oó]n)/i,
      /chec(a|ar)\s*(me\s*)?(mi\s*)?(internet|conexi[oó]n)/i,
      /diagn[oó]stic(a|ar)\s*(me\s*)?(mi\s*)?(internet|conexi[oó]n)/i,
      /internet\s*lento/i,
      /se\s*(me\s*)?cae/i,
      /intermiten/i,
      /luz\s*(roja|verde|naranja|parpade)/i,
      /no\s*(me\s*)?funciona/i,
      /falla/i,
      /problema.*conexi[óo]n/i,
      /conexi[oó]n.*problema/i,
      /se\s*desconecta/i,
      /baja\s*velocidad/i,
      /onu.*desconfigurad/i,
      /desconfigurad.*onu/i,
      /reiniciar\s*(la\s*)?onu/i,
      /reboot/i,
      /prio(ridad|ritario)/i,
      /sla/i,
      /tiempos?\s*(de\s*)?respuesta/i,
      /cu[aá]nto\s*(tarde|demora|tardan)/i,
      /atenci[oó]n/i,
    ],
  },

  {
    category: "ESCALACION",
    tool: "escalate_to_specialist",
    query: null,
    confidence: "alta",
    patterns: [
      /hablar\s*(con\s*)?(un\s|una\s)?(human[oa]|agente|operador|persona|asesor|alguien)/i,
      /quiero\s*(un\s|una\s)?(agente|operador|asesor|human[oa]|alguien)/i,
      /necesito\s*(un\s|una\s)?(agente|operador|asesor|human[oa]|ayuda\s+humana)/i,
      /p[aá]same\s*(con\s*)?(un\s|una\s)?(agente|operador|asesor|human[oa]|alguien)/i,
      /escalar/i,
      /comunicarme\s+con\s+(asesor|agente|operador|alguien|human[oa])/i,
      /reclamar/i,
      /reclamo\s*formal/i,
    ],
  },

  {
    category: "CIERRE_CONFIRMADO",
    tool: "close_conversation",
    query: null,
    confidence: "alta",
    patterns: [
      /gracias?\s*(,)?\s*(eso\s*es|es)\s*todo/i,
      /eso\s*(es|era)\s*todo/i,
      /no\s*necesito\s*(nada\s*)?m[áa]s/i,
      /nada\s*m[áa]s/i,
      /ya\s*(est[áa]|qued[óo])\s*(resuelto|solucionado|bien|todo|listo)/i,
      /ya\s*me\s*(ayudaste|ayudaron|resolvieron)/i,
      /era\s*(lo\s*que|todo\s*lo\s*que)\s*necesitaba/i,
      /problema\s*(resuelto|solucionado)/i,
      /no,?\s*(eso\s*es\s*todo|nada\s*m[áa]s|estoy\s*bien)/i,
      /todo\s*(bien|resuelto|listo|perfecto),?\s*gracia/i,
      /(cierra|cerrar)\s*(la\s*)?(conv|conve|chat|conversaci[oó]n|ticket)/i,
      /^cierra\s*esto$/i,
      /ya\s*terminamos/i,
      /^chao$/i,
      /^adi[oó]s$/i,
      /^bye$/i,
      /^hasta\s*luego$/i,
      /^nos\s*vemos$/i,
      /^no,?\s*tranqui/i,
      /^tranqui/i,
      /^no\s*te\s*preocupes/i,
      /^no,?\s*est[oá]y\s*bien/i,
      /^no,?\s*ya\s*(est[áa]|es\s*todo)/i,
      /^no,?\s*(no\s*)?hace\s*falta/i,
      /^no,?\s*as[ií]\s*est[áa]\s*bien/i,
      /^no,?\s*todo\s*bien/i,
      /^est[oá]y\s*bien/i,
      /^listo,?\s*gracias?/i,
      /^nada$/i,
      /^nada\s*nada/i,
      /^no,?\s*nada/i,
      /^ya\s*terminamos/i,
      /^ya\s*termin[ée]/i,
      /^d[ée]jalo\s*as[ií]/i,
      /^ci[ée]rrala/i,
    ],
  },

  {
    category: "CONSULTA_PERSONAL",
    tool: null,
    query: null,
    confidence: "alta",
    patterns: [
      /c[oó]mo\s*me\s*llamo/i,
      /cu[áa]l\s*es\s*mi\s*nombre/i,
      /me\s*puedes\s*decir\s*mi\s*nombre/i,
      /qui[ée]n\s*soy/i,
      /cu[áa]nto\s*debo/i,
      /mi\s*deuda/i,
      /tengo\s*deuda/i,
      /debo\s*(algo|plata|dinero)/i,
      /est[áa]\s*activo/i,
      /est[oó]y\s*(suspendido|cortado)/i,
      /mi\s*servicio/i,
      /mi\s*contrato/i,
      /mi\s*plan/i,
      /cu[áa]l\s*tengo/i,
      /cu[áa]l\s*es\s*mi\s*(plan|deuda|contrato|servicio)/i,
      /qu[ée]\s*(plan|velocidad|contrato)\s*tengo/i,
      /cu[áa]ntos?\s*contrato/i,
      /estado\s*(de\s*)?(mi\s*)?(servicio|cuenta|contrato)/i,
      /pago.*verificaci[oó]n/i,
      /verificaci[oó]n.*pago/i,
      /tengo.*pago.*pendiente/i,
      /alg[uú]n\s*pago/i,
    ],
  },

  {
    category: "SEGUIMIENTO",
    tool: null,
    query: null,
    confidence: "alta",
    patterns: [
      /no\s*respond/i,
      /incompleto/i,
      /falt[óa]/i,
      /contin[úu]a/i,
      /^s[ií],?\s*dale$/i,
      /^dale,?\s*s[ií]$/i,
      /^s[ií],?\s*(claro|exacto|correcto|contin[úu]a|sigue|m[aá]s)$/i,
      /^ok,?\s*(dale|contin[úu]a|sigue|m[aá]s)$/i,
      /^(s[ií]|si),?\s*(por\s*f[aá](?:v|b)?(?:o|0|i)?r|porfa|porfavor),?\s*(ap[úu]rate|r[aá]pido|dale|contin[úu]a|sigue)?$/i,
      /cambiar(me)?\s*(al|a)\s*(primer|segundo|tercer|tercero|cuarto|quinto)\s*plan/i,
      /^al\s+que\s+comienza\s+por/i,
      /^el\s+que\s+comienza\s+por/i,
      /^el\s+(primero|segundo|tercero|cuarto|quinto)$/i,
      /^la\s+(primera|segunda|tercera|cuarta|quinta)$/i,
      /^opci[oó]n\s*\d{1,2}$/i,
      /^n[uú]mero\s*\d{1,2}$/i,
      /^(el|la)\s+de\s+.+$/i,
      /m[áa]s\s*informaci[óo]n/i,
      /explica\s*mejor/i,
      /no\s*entend[ií]/i,
      /sigue/i,
      /termin(a|aste)/i,
      /repite/i,
      /otra\s*vez/i,
    ],
  },

  {
    category: "CONVERSACIONAL",
    tool: null,
    query: null,
    confidence: "alta",
    patterns: [
      /^hola$/i,
      /^buenas?$/i,
      /^buenos?\s*(d[ií]as?|tardes?|noches?)/i,
      /^gracias?$/i,
      /^ok$/i,
      /^perfecto$/i,
      /^[ée]pale$/i,
      /^epa$/i,
      /^qlq\??$/i,
      /^klk\??$/i,
      /^qu[ée]\s*tal$/i,
      /^c[oó]mo\s*est[aá]s\??$/i,
      /^c[oó]mo\s*te\s*va\??$/i,
      /^todo\s*bien\??$/i,
      /^hey$/i,
      /^mucho\s*gusto$/i,
      /^un\s+gusto$/i,
      /^igualmente$/i,
      /^encantad[oa]$/i,
      /^el\s+gusto\s+es\s*m[ií]o$/i,
      /^c[oó]mo\s*te\s*llamas?\??$/i,
      /^cu[áa]l\s*es\s*tu\s*nombre\??$/i,
      /^qui[ée]n\s*eres\s*t[uú]?\??$/i,
      /^eres\s*(un\s*)?(bot|robot|ia|asistente|humana?|persona|real)\??$/i,
      /^c[oó]mo\s*te\s*(dicen|llaman)\??$/i,
      /^tu\s*nombre\??$/i,
      /^(perfecto|genial|excelente|ok|okey|listo|dale|va|vale),?\s*(muchas\s*)?gracias/i,
      /^muchas\s*gracias/i,
      /^gracias\s*(por\s*todo|hermano|pana|amigo|bro)/i,
      /^dale$/i,
      /^va$/i,
      /^vale$/i,
      /^de\s*nada$/i,
      /^okey$/i,
      /^okie$/i,
      /^de\s*acuerdo$/i,
      /^entendido$/i,
      /^claro$/i,
      /^s[ií]$/i,
      /^a[hj][aá]$/i,
      /^ya\s*veo$/i,
      /^genial$/i,
      /^buen[oa]s?$/i,
      /^hola\s+susana/i,
      /^oye\s+susana/i,
      /^mira\s+susana/i,
    ],
    extraCheck: (msg) => msg.split(/\s+/).length <= 5,
  },
];

export const SISPROT_MENTION_FALLBACK: IntentClassification = {
  category: "INFO_EMPRESA",
  confidence: "media",
  suggestedTool: "search_knowledge_base",
  suggestedQuery: "información corporativa Sisprot",
  reasoning: "Menciona Sisprot — probable pregunta sobre la empresa",
};

export const UNKNOWN_INTENT: IntentClassification = {
  category: "DESCONOCIDO",
  confidence: "baja",
  suggestedTool: null,
  suggestedQuery: null,
  reasoning: "No se detectó patrón claro",
};
